[build]
  command = "npm ci"
  publish = "public"
  functions = "netlify/functions"

  [build.environment]
    SECRETS_SCAN_OMIT_KEYS = "NODE_ENV,PORT"
    SECRETS_SCAN_OMIT_PATHS = "README.md,Dockerfile,docker-compose.yml,src/index.js"

[functions]
  node_bundler = "zisi"
  external_node_modules = [
    "express",
    "hbs",
    "mongoose",
    "bcryptjs",
    "jsonwebtoken",
    "cookie-parser",
    "serverless-http",
  ]
  included_files = ["templates/**", "public/**"]

[functions.server]
  timeout = 26
  memory = 1024

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
